version: '3.8'

services:
  # Frontend application
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - VITE_API_URL=${VITE_API_URL:-http://localhost:3001/api}
        - VITE_AUTH_ENDPOINT=${VITE_AUTH_ENDPOINT:-/auth}
        - VITE_LEADS_ENDPOINT=${VITE_LEADS_ENDPOINT:-/leads}
        - VITE_CAMPAIGNS_ENDPOINT=${VITE_CAMPAIGNS_ENDPOINT:-/campaigns}
        - VITE_EMAIL_ENDPOINT=${VITE_EMAIL_ENDPOINT:-/email}
        - VITE_SEARCH_ENDPOINT=${VITE_SEARCH_ENDPOINT:-/search}
        - VITE_WEB_READER_ENDPOINT=${VITE_WEB_READER_ENDPOINT:-/web-reader}
        - VITE_APP_NAME=${VITE_APP_NAME:-Marketing Automation Platform}
        - VITE_APP_VERSION=${VITE_APP_VERSION:-1.0.0}
    ports:
      - "3000:80"
    environment:
      - NODE_ENV=production
    networks:
      - app-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Optional: Add your backend service here
  # backend:
  #   image: your-backend-image
  #   ports:
  #     - "3001:3001"
  #   environment:
  #     - NODE_ENV=production
  #     - DATABASE_URL=${DATABASE_URL}
  #   networks:
  #     - app-network
  #   restart: unless-stopped

networks:
  app-network:
    driver: bridge

# Optional: Add volumes for persistent data
volumes:
  app-data:
    driver: local